# Generated by Django 4.2.3 on 2023-07-31 02:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_app', '0003_userprofiel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfiel',
            new_name='UserProfile',
        ),
    ]
