# Generated by Django 4.2.3 on 2023-08-01 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=datetime.datetime(2023, 8, 1, 1, 20, 21, 518785, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
    ]
