# Generated by Django 4.2.3 on 2023-08-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_newspaper_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newspaper',
            new_name='Newsletter',
        ),
    ]
